spring:
  application:
    name: collector

logging:
  level:
    ru.yandex.practicum: TRACE
    org:
      springframework: ERROR
      apache.kafka: ERROR

kafka:
  topic:
    sensor: telemetry.sensors.v1
    hub: telemetry.hubs.v1
  bootstrap:
    server: localhost:9092

collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "telemetry.collector"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
        "schema.registry.url": http://localhost:8081
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1